# Generated by Django 5.2.12 on 2026-04-06 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perpustakaan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buku',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='covers'),
        ),
        migrations.AlterField(
            model_name='peminjaman',
            name='status',
            field=models.CharField(choices=[('dipinjam', 'Dipinjam'), ('kembali', 'Dikembalikan'), ('terlambat', 'Terlambat'), ('hilang', 'Hilang')], default='dipinjam', max_length=20),
        ),
    ]
