# Generated by Django 6.0.3 on 2026-04-07 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perpustakaan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PengaturanSistem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denda_per_hari', models.IntegerField(default=2000, help_text='Nominal denda per hari keterlambatan (Rupiah)')),
                ('denda_hilang_buku', models.IntegerField(default=100000, help_text='Nominal denda jika buku hilang (Rupiah)')),
                ('batas_hari_pinjam', models.IntegerField(default=7, help_text='Batas maksimal hari peminjaman buku')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pengaturan Sistem',
                'verbose_name_plural': 'Pengaturan Sistem',
            },
        ),
        migrations.AlterField(
            model_name='peminjaman',
            name='status',
            field=models.CharField(choices=[('dipinjam', 'Dipinjam'), ('kembali', 'Dikembalikan'), ('terlambat', 'Terlambat'), ('hilang', 'Hilang')], default='dipinjam', max_length=20),
        ),
    ]
